services:
  # Сервис для Django
  web:
    build: .
    container_name: portfolio
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_HOST_ADDRESS=${EMAIL_HOST_ADDRESS}
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

  # Сервис для PostgreSQL (или любой другой БД)
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge

volumes:
  postgres_data:
